[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; --- AJUSTE EXATO PARA CHIP DE 8MB SEM PSRAM ---
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.filesystem = littlefs

; Removemos todas as flags de PSRAM e de 16MB para corrigir o compilador
build_flags = 

lib_deps = 
    jrowberg/I2Cdevlib-MPU6050@^1.0.0
    esp32async/ESPAsyncWebServer@^3.11.0
    bblanchon/ArduinoJson@^7.2.2